import type { Metadata } from "next";
import { Playfair } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "./ConvexClientProvider";
import Header from "./_components/Header";

export const metadata: Metadata = {
  title: "AI Trip Planner",
  description: "Generated by create next app",
};

const playfair = Playfair({
  subsets: ["latin"],
  variable: "--font-playfair",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
   
       <html lang="en" className={playfair.variable}>
      <body className={playfair.className}>
        <ClerkProvider>
          <ConvexClientProvider>
            <Provider>
              <Header />
              {children}
            </Provider>
          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
    
    
  );
}
